# PER-PFT F parameters (ADR 0126) — the table gate, the byte-identical default, and the direction of
# the fix. `FDiffFastCore` used to hand every tree beech's parameters; ADR 0125 measured that this is a
# 6x maintenance-respiration error at every tropical cell (F's annual carbon balance went NEGATIVE where
# the C's was +1073 gC/m2/yr). These items check the three things that can silently break:
#   1. the LITERALS in `src/fdiff.jl` still equal the live C parameter file, value by value, via the
#      committed table `references/M_pft_fdiff_params.csv` (generated by `cpp -P`, ADR 0031's rule that
#      a physical constant lives in exactly one place);
#   2. the channel is OFF by default and a beech-only stand is BYTE-IDENTICAL with it on (guardrail 4) —
#      which is only true because `pft_*(3)` returns F's shipped defaults exactly;
#   3. switching it on moves the tropical stand's carbon balance UP and the boreal needleleaf's crown
#      cover DOWN, i.e. in the directions the per-PFT values imply.

# The committed table IS the C parameter file, so this item is what makes the Julia literals a read of
# it rather than a transcription of it. Regenerate with
# `python3 scripts/build_pft_fdiff_params_reference.py` (CHECK=1 to verify against the C first).
@testitem "per-PFT F parameters match the committed C table, value by value (ADR 0126)" tags = [:unit, :fdiff] begin
    using LPJmLFITEmulator.FDiff
    using LPJmLFITEmulator.Allometry: TreeAllometry, gymnosperm
    using Test

    path = joinpath(@__DIR__, "references", "M_pft_fdiff_params.csv")
    lines = [l for l in readlines(path) if !isempty(strip(l)) && !startswith(strip(l), "#")]
    hdr = split(strip(lines[1]), ',')
    rows = [split(strip(l), ',') for l in lines[2:end]]
    col = Dict(String(hdr[j]) => [r[j] for r in rows] for j in eachindex(hdr))
    @test length(rows) == 10                      # the ten natural PFTs, ids 0-9
    num(k, r) = parse(Float64, col[k][r])

    for r in 1:10
        id = parse(Int, col["pft_id"][r])
        @test id == r - 1                          # rows are in scan order
        resp = FDiff.pft_respparams(id)
        ts = FDiff.pft_tempstressparams(id)
        al = FDiff.pft_allocparams(id)
        am = FDiff.pft_allometry(id)
        tr = FDiff.pft_canopy_traits(id)
        ph = FDiff.pft_phys(id)

        # respiration — the parameter ADR 0125 convicted
        @test resp.respcoeff == num("respcoeff", r)
        @test resp.cn_root == num("cn_root", r)
        # photosynthesis temperature limits (NOT `temp_stressed`, NOT the establishment `temp`)
        @test ts.temp_photos_low == num("temp_photos_low", r)
        @test ts.temp_photos_high == num("temp_photos_high", r)
        @test ts.temp_co2_low == num("temp_co2_low", r)
        @test ts.temp_co2_high == num("temp_co2_high", r)
        # turnover: the C stores a RESIDENCE TIME in years, F a RATE per year
        @test al.turnover_leaf == 1.0 / num("turnover_leaf_yr", r)
        @test al.turnover_root == 1.0 / num("turnover_root_yr", r)
        @test al.turnover_leaf == num("turnover_leaf_rate", r)
        @test al.turnover_root == num("turnover_root_rate", r)
        @test al.lmro_ratio == num("lmro_ratio", r)
        @test al.lmro_offset == num("lmro_offset", r)
        @test al.reprod_cost == num("reprod_cost", r)
        # the per-individual canopy constants + Beer-Lambert extinction
        @test tr.gmin == num("gmin", r)
        @test tr.emax == num("emax", r)
        @test tr.intc == num("intc", r)
        @test tr.alphaa == num("alphaa", r)
        @test tr.albedo_leaf == num("albedo_leaf", r)
        @test tr.albedo_stem == num("albedo_stem", r)
        @test tr.albedo_litter == num("albedo_litter", r)
        @test tr.snowcanopyfrac == num("snowcanopyfrac", r)
        @test tr.k_beer == num("lightextcoeff", r)
        @test am.k_beer == num("lightextcoeff", r)
        @test tr.path == (col["path"][r] == "C4" ? :c4 : :c3)
        # the bundle is exactly the five lookups, so a caller cannot get a mixed set
        @test ph.resp == resp && ph.alloc == al && ph.allom == am && ph.tstress == ts
        @test ph.gmin == tr.gmin
        if col["type"][r] == "tree"
            @test al.turnover_sapwood == 1.0 / num("turnover_sapwood_yr", r)
            @test am.allom1 == num("allom1", r)
            @test am.allom2 == num("allom2", r)
            @test am.allom3 == num("allom3", r)
            @test am.kpr == num("kpr", r)
            @test am.k_latosa == num("k_latosa", r)
            @test am.crownarea_max == num("crownarea_max", r)
            @test am.crownlength == num("crownlength", r)
            @test am.height_max == num("height_max", r)
            # angiosperm vs gymnosperm is the leaftype, not the id
            expect = col["leaftype"][r] == "needleleaved" ?
                gymnosperm(TreeAllometry{Float64}) : TreeAllometry{Float64}()
            @test am.allom1 == expect.allom1 && am.kpr == expect.kpr
        else
            @test col["turnover_sapwood_yr"][r] == ""      # grass has no woody pool
            @test al.turnover_sapwood == FDiff.AllocParams{Float64}().turnover_sapwood
        end
    end

    # the two facts the whole change rests on, asserted directly (ADR 0125 §5)
    @test FDiff.pft_respparams(0).respcoeff == 0.2         # tropical broadleaved evergreen
    @test all(FDiff.pft_respparams(i).respcoeff == 1.2 for i in 1:6)
    @test FDiff.pft_allometry(6).k_beer == 0.45            # larch — needleleaved
    @test FDiff.pft_allometry(3).k_beer == 0.59            # beech — broadleaved

    # ids 10+ are crops (`landuse:"no"` ⇒ never simulated); asking for one is a caller error, not a
    # silent fall-back to beech, which is exactly the failure mode ADR 0126 removes.
    @test_throws ArgumentError FDiff.pft_respparams(10)
    @test_throws ArgumentError FDiff.pft_phys(-1)

    # Float32 propagates through every lookup (the core is parametric in T)
    @test FDiff.pft_respparams(0, Float32).respcoeff === 0.2f0
    @test FDiff.pft_phys(6, Float32) isa FDiff.PFTPhys{Float32}
    @test eltype(FDiff.pft_phys([0, 3, 6], Float32)) === FDiff.PFTPhys{Float32}
end

# GUARDRAIL 4: `pft_*(3)` must BE F's shipped beech configuration, otherwise "opt-in, default
# byte-identical" cannot hold — and `pft_allocparams(8)` must be the shipped grass set for the same
# reason on the grass path. These four identities are the entire basis of the byte-identity item below.
@testitem "per-PFT lookups at beech/grass reproduce F's shipped parameter sets exactly" tags = [:unit, :fdiff] begin
    using LPJmLFITEmulator.FDiff
    using LPJmLFITEmulator.Allometry: TreeAllometry, gymnosperm
    using Test

    p = FDiff.tebs_params(Float64)
    @test FDiff.pft_respparams(3) == p.resp
    @test FDiff.pft_tempstressparams(3) == p.tstress
    @test FDiff.pft_allocparams(3) == FDiff.tebs_allocparams()
    @test FDiff.pft_allometry(3) == TreeAllometry{Float64}()
    @test FDiff.pft_allocparams(8) == FDiff.grass_allocparams()
    # beech's gmin/emax are the ones `tebs_params` switches on (1.0 / 10.0)
    @test FDiff.pft_canopy_traits(3).gmin == p.water.gmin
    @test FDiff.pft_canopy_traits(3).emax == p.water.emax
end

# The behavioural half of guardrail 4 plus the DIRECTION of the fix, on a synthetic two-cohort patch
# (no committed data needed). Three claims:
#   (a) `per_pft_params` is OFF by default and the core then carries no bundles at all;
#   (b) a BEECH-ONLY stand is byte-identical with the channel on — the property that lets the feature
#       ship without moving a single committed baseline;
#   (c) turning it on for a TROPICAL stand raises the annual assimilate (respcoeff 1.2 -> 0.2) and for a
#       NEEDLELEAVED one lowers crown cover (k_beer 0.59 -> 0.45), the two signs ADR 0125 predicts.
@testitem "per-PFT parameters: off by default, beech-identical, and moves the tropical/boreal stand the predicted way" tags = [:unit, :fdiff, :coupling] begin
    using LPJmLFITEmulator
    using LPJmLFITEmulator.FDiff
    using LPJmLFITEmulator.FDiff: PhotoParams, TempStressParams, TreePools, Individual
    using Test

    T = Float64
    sd = Float64[200, 300, 500, fill(1000.0, 19)..., 3000]
    soil = FDiff.hainich_soilcolumn(;
        whcs = [0.12 * d for d in sd], rootdist = fill(1 / length(sd), length(sd)), soildepth = sd,
    )
    # two cohorts with a LARGE woody pool, so maintenance respiration (∝ c_sapwood/cn_sapwood) is a
    # first-order term and the respcoeff arm is unambiguous rather than a rounding difference.
    pools0 = [
        TreePools{T}(300.0, 40000.0, 60000.0, 300.0, 22.0, 30.0, 1 / 225, 0.01986, 2.0e5, false),
        TreePools{T}(200.0, 25000.0, 35000.0, 200.0, 16.0, 20.0, 1 / 225, 0.025, 2.5e5, false),
    ]
    tmpls = [
        Individual{T}(
                0.3, 0.0, 0.55, 0.15, 10.0, 40000.0, 300.0, 6.0, 0.02, 0.04, 0.1, 0.4, 1 / 225,
                PhotoParams{T}(; path = :c3, issla = true, sla = 0.01986),
                TempStressParams{T}(; temp_photos_low = 20.0, temp_photos_high = 30.0), false,
            ) for _ in 1:2
    ]
    mkcore(ids, on) = FDiffFastCore(
        copy(pools0), tmpls, soil, 51.25; params = FDiff.tebs_params(T), pft_ids = ids, per_pft_params = on,
    )
    function runyear!(core)
        st = SharedState(; w = fill(0.7, LPJmLFITEmulator.NSOILLAYER))
        bc = LPJmLFITEmulator.stand_structure_tof(core)
        gpp = 0.0
        for d in 1:365
            f = AtmForcing(;
                tair = 288.15 + 8sin(2π * d / 365), swdown = 200.0, lwdown = 320.0, precip = 3.0,
                qair = 0.008, co2 = 380.0, wind = 2.0, psurf = 1.0e5,
            )
            gpp += LPJmLFITEmulator.step!(core, st, bc, f).gpp
        end
        ftos = LPJmLFITEmulator.annual_step!(core, st)
        fpc = sum(FDiff._treepools_fpc(core.pools[i], FDiff.pft_allometry(core.pft_ids[i])) for i in 1:2)
        return (; gpp, bm_inc = Float64(ftos.bm_inc), fpc, h = [p.height for p in core.pools])
    end

    # (a) OFF by default ⇒ no bundles at all, and every rebuilt individual keeps its template's tstress
    dflt = mkcore([3, 6], false)
    @test dflt.pft_phys === nothing
    @test all(dflt.inds[i].tstress == tmpls[i].tstress for i in 1:2)
    on = mkcore([3, 6], true)
    @test on.pft_phys !== nothing
    @test length(on.pft_phys) == 2
    @test on.pft_phys[1].resp == FDiff.pft_respparams(3)
    @test on.pft_phys[2].resp == FDiff.pft_respparams(6)
    @test on.inds[2].tstress == FDiff.pft_tempstressparams(6)      # larch: temp_photos 15/25, overridden
    @test on.inds[2].tstress != tmpls[2].tstress

    # (b) BEECH-ONLY: byte-identical with the channel on (guardrail 4)
    b_off = runyear!(mkcore([3, 3], false))
    b_on = runyear!(mkcore([3, 3], true))
    @test b_on.gpp === b_off.gpp
    @test b_on.bm_inc === b_off.bm_inc
    @test b_on.h == b_off.h
    @test b_on.fpc === b_off.fpc

    # (c) TROPICAL (id 0, respcoeff 0.2 against beech's 1.2): the same stand keeps far more of its
    # assimilate. This is the sign — not the size — of ADR 0125's Amazon result (−223 → +1206 gC/m²/yr).
    t_off = runyear!(mkcore([3, 3], false))
    t_on = runyear!(mkcore([0, 0], true))
    @test t_on.bm_inc > t_off.bm_inc
    # and the mechanism is respiration, not photosynthesis: id 0's own maintenance coefficient is 6x lower
    @test FDiff.pft_respparams(0).respcoeff * 6 ≈ FDiff.pft_respparams(3).respcoeff

    # NEEDLELEAVED (ids 1/4/6): a lower Beer-Lambert extinction absorbs less light per unit LAI, so the
    # same leaf carbon covers less ground. Compare the fpc of ONE cohort at fixed pools, no physics.
    fpc_bl = FDiff._treepools_fpc(pools0[1], FDiff.pft_allometry(3))
    fpc_nl = FDiff._treepools_fpc(pools0[1], FDiff.pft_allometry(6))
    @test fpc_nl < fpc_bl
end

# The per-PFT channel is F-side only: S's demography rebuilds the roster with the core's single shared
# allometry, so enabling it with a slow emulator attached would run two `k_beer` bases in one simulation.
# `run_coupled_cell` must REFUSE that rather than report a mixed-basis number (ADR 0060's lesson).
@testitem "run_coupled_cell refuses per-PFT F parameters together with a slow emulator (ADR 0126)" tags = [:unit, :coupling] begin
    using LPJmLFITEmulator
    using LPJmLFITEmulator.FDiff
    using LPJmLFITEmulator.FDiff: PhotoParams, TempStressParams, TreePools, Individual
    using Test

    T = Float64
    sd = Float64[200, 300, 500, fill(1000.0, 19)..., 3000]
    soil = FDiff.hainich_soilcolumn(;
        whcs = [0.12 * d for d in sd], rootdist = fill(1 / length(sd), length(sd)), soildepth = sd,
    )
    pools = [TreePools{T}(300.0, 40000.0, 60000.0, 300.0, 22.0, 30.0, 1 / 225, 0.01986, 2.0e5, false)]
    tmpls = [
        Individual{T}(
            0.3, 0.0, 0.55, 0.15, 10.0, 40000.0, 300.0, 6.0, 0.02, 0.04, 0.1, 0.4, 1 / 225,
            PhotoParams{T}(; path = :c3, issla = true, sla = 0.01986),
            TempStressParams{T}(; temp_photos_low = 20.0, temp_photos_high = 30.0), false,
        ),
    ]
    core = FDiffFastCore(copy(pools), tmpls, soil, 51.25; pft_ids = [3], per_pft_params = true)
    clo = SEBEnergyClosure(; t_soil0 = 283.15)
    state = SharedState(; w = fill(0.7, LPJmLFITEmulator.NSOILLAYER))
    forcings = [
        AtmForcing(;
                tair = 288.15, swdown = 200.0, lwdown = 320.0, precip = 3.0, qair = 0.008, co2 = 380.0,
                wind = 2.0, psurf = 1.0e5,
            ) for _ in 1:5
    ]
    slow = DemographicSlowEmulator(core)
    @test_throws ErrorException run_coupled_cell(core, clo, state, forcings; slow = slow, days_per_year = 5)
    # ... while the same run with `slow = nothing` is allowed (the arm ADR 0126 is measured on)
    out = run_coupled_cell(core, clo, state, forcings; days_per_year = 5)
    @test all(isfinite, out.gpp)
end
