#!/usr/bin/env python3
"""explore_de_tab_features.py — LINE X, Germany data-driven emulator, design track A-TAB, item A1:
FEATURE MODULE + STRATIFIED TRAINING SAMPLES for the per-tree gradient-boosted transition heads.

ONE feature code path for training and rollout. Every feature is computed by `assemble()` from a frame of RAW
columns; the raw frame comes from
  training  `raw_training_frame()`  = SH3 transition table (explore_de_sh_trans) + SH4 patch cover-loss history
            + tr.join_climate() (the only allowed climate join) + SH1 own-GCM 1985-2014 climatology + soil code
  rollout   `roster_raw(state, clim_y, clim_y1)` = the engine's RosterState (explore_de_engine) + the climate
            provider's frames of year y and y+1 + the same climatology/soil tables.
`audit` rebuilds the rollout frame from an SH5 initial state and checks every feature against the training frame
of the same trees and year (the proof that every input is regenerated by carried rollout state).

FEATURE SETS (names as produced by assemble())
  B0 state    Type, the 6 traits, Height, log_agb, log_vegc, LAI, fpc_ind, D95, Age, c_y, G_y, d_agb_prev,
              rel_dagb_prev, is_new; patch n_live, sum_fpc, sum_agb, height_rank, rel_rank, fpc_above, grass<t>_*,
              cell_stems_per_patch, the cover-loss ring flo0..flo4 + flo_m5_19 (fraction of the patch's printed
              living crown cover lost in each of the last years); soil_code; c85_* (own-GCM 1985-2014 climatology)
  B1 climate  a_<f>_y and a_<f>_y1 (anomaly vs the cell's own-GCM 1985-2014 mean) for 17 annual features, the
              tree's OWN-PFT temperature-stress-day anomaly (y, y+1) and absolute count (y+1), the 20-yr trailing
              anomalies of tcold/twarm/gdd5 (y+1), and ABSOLUTE tmean_ann / twarm_month of y+1
  B1 model inputs = B1 + (Type, log_agb): the climate booster may modulate by PFT and size, nothing else.
  CO2, wind, lon/lat and the cell id are never features.

SPLIT  `split_spec(name)` — DEV-A: train = the registry's role == "train" members (MPI-ESM1-2-HR seed 1:
  Historical 1985-2013 + ssp126 + ssp370 2014-2043) on the dev cells of block folds 1-4; one of folds 1-4 (seeded
  random) is the early-stopping validation fold; held out: fold-5 cells (F5), ACCESS-CM2 seed 1 (GCM), MPI ssp245
  seed 2 (SCEN), MPI seed 2 Historical/ssp126/ssp370 (SEED2). Never trained on.

SAMPLES  /p/tmp/jamirp/X_de/tab/samples/<split>/
  train/<member>/y<Y>.parquet   folds 1-4 rows: ALL rows with c_y >= 1 or c_y1 >= 1 or G_y < 0 or G_y1 < 0 or
                                fate_y1 >= 1 (stratum 1, weight 1) + rows with u_hash < 0.10 of the rest
                                (stratum 0, weight 10 = inverse inclusion probability); column `fold`
  eval/<set>/<member>/y<Y>.parquet  u_hash < EVAL_FRAC unweighted rows of every held-out set
  recruits/<role>/<member>.parquet  recruit rows (Type target) + patch/cell composition by Type (heads H8/H9)
STAGES  samples [--member M] | recruits | audit | submit | report
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import sys
import time

import numpy as np
import polars as pl

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "scripts"))
import explore_de_sh_rules as rl  # noqa: E402
import explore_de_sh_trans as tr  # noqa: E402

XDE = tr.XDE
TAB = os.environ.get("XDE_TAB", os.path.join(XDE, "tab"))
SAMPLES = os.path.join(TAB, "samples")
PATCHT = os.path.join(XDE, "shared", "patch")
RECRT = os.path.join(XDE, "shared", "recruits")
C8514 = os.path.join(XDE, "shared", "climate", "clim8514.parquet")
STATIC = os.path.join(XDE, "climate", "cell_static.parquet")
STATUS = os.path.join(XDE, "_status", "A1.md")
REPORT = os.path.join(XDE, "_reports", "r2_A1.json")
PY = tr.PY
CELLSET = "dev"
NLAG = 20
REST_FRAC = 0.10
EVAL_FRAC = 0.02
MAX_TREE_TYPE = tr.MAX_TREE_TYPE

# ------------------------------------------------------------------------------------------------ feature lists
CLIM_F = ["tmean_ann", "twarm_month", "tcold_month", "gdd5", "frost_days", "days_gt30", "prec_ann", "prec_jja",
          "prec_amjjas", "cwb_jja", "cwb_amjjas", "cwb_min3", "dry_spell_max", "vpd_jja", "vpd_win10_sum",
          "swdown_ann", "rh_jja"]
TR20 = ["tcold_month_tr20", "twarm_month_tr20", "gdd5_tr20"]
ABS_Y1 = ["tmean_ann", "twarm_month"]
ELIG_ABS = ["tcold_month_tr20", "twarm_month_tr20", "gdd5", "prec_ann"]  # rl.eligible inputs (recruit head)
TSTRESS = [f"tstress_pft{k}" for k in range(MAX_TREE_TYPE + 1)]
C85_F = ["tmean_ann", "tcold_month", "twarm_month", "gdd5", "frost_days", "prec_ann", "prec_jja", "cwb_jja",
         "cwb_amjjas", "cwb_min3", "dry_spell_max", "vpd_jja", "vpd_win10_sum", "swdown_ann", "rh_jja"]
# climate columns requested from tr.join_climate (both years)
CLIM_COLS = ([f"anom_{f}" for f in CLIM_F] + [f"anom_{t}" for t in TSTRESS] + TSTRESS + [f"anom_{f}" for f in TR20]
             + sorted(set(ABS_Y1 + ELIG_ABS)))
TRAITS = list(tr.TRAITS)
GRASS_TYPES = [8]  # detected from the tables at build time; checked in `samples`
# global venue: grasses 7, 8, 9 (XDE_GRASS_TYPES="7,8,9"); default = Germany, unchanged
GRASS_TYPES = [int(t) for t in os.environ.get("XDE_GRASS_TYPES", ",".join(map(str, GRASS_TYPES))).split(",")]
CAT = ["Type", "soil_code"]


def grass_cols(types=None):
    return [f"grass{t}_{v}" for t in (types or GRASS_TYPES) for v in ("fpc", "LAI", "agb")]


B0 = (["Type"] + TRAITS + ["Height", "log_agb", "log_vegc", "LAI", "fpc_ind", "D95", "Age", "c_y", "G_y",
                           "d_agb_prev", "rel_dagb_prev", "is_new",
                           "n_live", "sum_fpc", "sum_agb", "height_rank", "rel_rank", "fpc_above"]
      + grass_cols() + ["cell_stems_per_patch"] + [f"flo{k}" for k in range(5)] + ["flo_m5_19", "soil_code"]
      + [f"c85_{f}" for f in C85_F])
B1 = ([f"a_{f}_{s}" for f in CLIM_F for s in ("y", "y1")] + ["a_tstress_own_y", "a_tstress_own_y1",
                                                             "tstress_own_y1"]
      + [f"a_{f}_y1" for f in TR20] + [f"{f}_y1" for f in ABS_Y1])
B1_MOD = ["Type", "log_agb"]
B1_IN = B1 + B1_MOD
# hidden state of y+1 sampled by earlier heads in the rollout (true values in training = teacher forcing)
NEXT = ["G_y1", "c_y1", "dlog_agb_y1", "dlog_vegc_y1"]
SURV_EXTRA = ["G_y1", "c_y1", "resist"]
# raw columns the rollout frame must provide (and the training frame carries)
RAW_TREE = ["Type"] + TRAITS + ["Height", "agb", "vegc", "LAI", "fpc_ind", "D95", "Age", "c_y", "G_y", "d_agb_prev",
                                "is_new_y"]
RAW_PATCH = ["n_live", "sum_fpc", "sum_agb", "height_rank", "fpc_above", "cell_stems_per_patch"] + grass_cols()
RAW_LOSS = [f"frac_loss_lag{k}" for k in range(NLAG)]
RAW_CLIM = [f"{c}_{s}" for c in CLIM_COLS for s in ("y", "y1")]
TARGETS = ["fate_y1", "hard_y1", "Height_y1", "agb_y1", "vegc_y1", "LAI_y1", "fpc_ind_y1", "D95_y1", "c_y1", "G_y1",
           "cenG_y1", "cenG_y", "mort_y1", "mort_npp_y1", "mort_age_y1", "mort_water_y1", "mort_temp_y1", "W_y1",
           "is_recruit_y", "is_reentry_y", "rh_on_y1", "bin_feb2026_y1"]
IDS = ["member", "gcm", "traj", "seed", "Year", "Cell", "Patch", "ID", "sla_i", "wd_i", "u_hash"]


def status(msg: str):
    os.makedirs(os.path.dirname(STATUS), exist_ok=True)
    line = f"- {time.strftime('%Y-%m-%d %H:%M')} {msg}"
    with open(STATUS, "a") as fh:
        fh.write(line + "\n")
    print(line, flush=True)


# ------------------------------------------------------------------------------------------------ split
def split_spec(name: str = "DEV-A", val_seed: int = 20261002) -> dict:
    """Members and cells of a split, from the SH0 registry (nothing hard-coded except the held-out set recipe)."""
    reg = pl.read_parquet(os.path.join(tr.REG, "splits.parquet")).filter(pl.col("split") == name)
    mem, _, folds = tr.registry()
    use = set(tr.usable_members(mem))
    train = sorted(set(reg.filter(pl.col("role") == "train")["src_member"].to_list()) & use)
    assert train, f"no training members for {name}"
    rows = {m: tr.member_row(mem, m) for m in use}
    tgcm = {rows[m]["gcm"] for m in train}
    tseed = {int(rows[m]["seed"]) for m in train}
    tscen = {rows[m]["scen"] for m in train}
    dev = folds.filter(pl.col("is_dev"))
    rng = np.random.default_rng(val_seed)
    val_fold = int(rng.integers(1, 5))
    held = {
        # spatial hold-out: the training members' fold-5 cells
        "F5": train,
        # held-out climate model: other GCM, the training seed, every usable scenario
        "GCM": sorted(m for m in use if rows[m]["gcm"] not in tgcm and int(rows[m]["seed"]) in tseed),
        # held-out scenario (+ binary): training GCM, ssp245 scored against seed 2 (registry test_truth)
        "SCEN": sorted(set(reg.filter(pl.col("role") == "test_truth")["src_member"].to_list()) & use
                       - set(train) - {m for m in use if rows[m]["gcm"] not in tgcm}),
        # held-out seed: the training GCM's other seed in the training scenarios
        "SEED2": sorted(m for m in use if rows[m]["gcm"] in tgcm and int(rows[m]["seed"]) not in tseed
                        and rows[m]["scen"] in tscen),
    }
    held["SCEN"] = [m for m in held["SCEN"] if rows[m]["scen"] != "Historical"]
    return {"split": name, "train": train, "val_fold": val_fold, "val_seed": val_seed,
            "train_folds": [1, 2, 3, 4], "heldout_fold": 5,
            "cells_train": sorted(dev.filter(pl.col("fold") <= 4)["Cell"].to_list()),
            "cells_f5": sorted(dev.filter(pl.col("fold") == 5)["Cell"].to_list()),
            "cells_dev": sorted(dev["Cell"].to_list()),
            "fold_of": dict(zip(dev["Cell"].to_list(), dev["fold"].to_list(), strict=True)),
            "heldout": held, "rows": {m: {k: rows[m][k] for k in ("gcm", "scen", "seed", "bin_feb2026", "npatch")}
                                      for m in use}}


def trans_files(member: str) -> list[str]:
    return sorted(glob.glob(os.path.join(tr.TRANS, CELLSET, member, "cb=*", "y*.parquet")))


def patch_file(member: str, year: int) -> str:
    f = glob.glob(os.path.join(PATCHT, CELLSET, member, "cb=*", f"y{year}.parquet"))
    assert len(f) == 1, (member, year, f)
    return f[0]


# ------------------------------------------------------------------------------------------------ static tables
_STATIC_CACHE: dict = {}


def statics(gcm: str) -> pl.DataFrame:
    """Per cell: soil_code + own-GCM 1985-2014 climatology c85_* (float32)."""
    if gcm not in _STATIC_CACHE:
        c8 = pl.read_parquet(C8514).filter(pl.col("gcm") == gcm).select(
            pl.col("Cell").cast(pl.Int16), *[pl.col(f).cast(pl.Float32).alias(f"c85_{f}") for f in C85_F])
        st = pl.read_parquet(STATIC).select(pl.col("Cell").cast(pl.Int16), pl.col("soil_code").cast(pl.Int16))
        _STATIC_CACHE[gcm] = st.join(c8, on="Cell", how="inner")
    return _STATIC_CACHE[gcm]


# ------------------------------------------------------------------------------------------------ THE assembly
def assemble(df, P=None):
    """Raw columns -> every feature (B0, B1 and the derived inputs). Works on DataFrame and LazyFrame. The SAME
    function is applied to the training frame and to the rollout frame."""
    P = rl.load_params() if P is None else P
    f32 = pl.Float32
    resist = P["resist"]
    own = lambda base: pl.coalesce([pl.when(pl.col("Type") == k).then(pl.col(f"{base.format(k)}").cast(f32))  # noqa: E731
                                     for k in range(MAX_TREE_TYPE + 1)])
    lag = [pl.col(f"frac_loss_lag{k}").cast(f32) for k in range(NLAG)]
    ex = [
        pl.col("agb").cast(f32).log().alias("log_agb"),
        pl.col("vegc").cast(f32).log().alias("log_vegc"),
        (pl.col("d_agb_prev").cast(f32) / pl.col("agb").cast(f32)).alias("rel_dagb_prev"),
        pl.col("is_new_y").fill_null(False).cast(f32).alias("is_new"),
        (pl.col("height_rank").cast(f32) / pl.col("n_live").cast(f32)).alias("rel_rank"),
        *[lag[k].alias(f"flo{k}") for k in range(5)],
        pl.mean_horizontal(lag[5:]).alias("flo_m5_19"),
        *[pl.col(f"anom_{f}_{s}").cast(f32).alias(f"a_{f}_{s}") for f in CLIM_F for s in ("y", "y1")],
        own("anom_tstress_pft{}_y").alias("a_tstress_own_y"),
        own("anom_tstress_pft{}_y1").alias("a_tstress_own_y1"),
        own("tstress_pft{}_y1").alias("tstress_own_y1"),
        *[pl.col(f"anom_{f}_y1").cast(f32).alias(f"a_{f}_y1") for f in TR20],
        pl.col("Type").replace_strict(list(range(len(resist))), [float(x) for x in resist],
                                      return_dtype=f32).alias("resist"),
    ]
    return df.with_columns(ex)


def to_matrix(df: pl.DataFrame, cols: list[str]) -> np.ndarray:
    return df.select([pl.col(c).cast(pl.Float32) for c in cols]).to_numpy().astype(np.float32, copy=False)


# ------------------------------------------------------------------------------------------------ training frame
def raw_training_frame(member: str, year: int, cells: list[int]) -> pl.LazyFrame:
    """SH3 rows of (member, y) on `cells`, with the SH4 cover-loss history of the tree's patch, the climate of y and
    y+1 (tr.join_climate) and the static/climatology columns."""
    files = [f for f in trans_files(member) if f.endswith(f"y{year}.parquet")]
    assert len(files) == 1, (member, year, files)
    lf = pl.scan_parquet(files[0]).filter(pl.col("Cell").is_in(cells))
    ph = pl.scan_parquet(patch_file(member, year)).select(
        "Cell", "Patch", "Year", *RAW_LOSS, "hist_years")
    lf = lf.join(ph, on=["Cell", "Patch", "Year"], how="left")
    lf = tr.join_climate(lf, cols=CLIM_COLS, years=("y", "y1"), ext=True)
    gcm = tr.member_row(tr.registry()[0], member)["gcm"]
    lf = lf.join(statics(gcm).lazy(), on="Cell", how="left")
    return lf


def sample_member(spec: dict, member: str, out_root: str, mode: str, frac: float, cells: list[int]):
    """mode 'train' (stratified + IP weights) or 'eval' (u_hash < frac, unweighted)."""
    od = os.path.join(out_root, member)
    os.makedirs(od, exist_ok=True)
    years = sorted(int(os.path.basename(f)[1:5]) for f in trans_files(member))
    fold = pl.DataFrame({"Cell": list(spec["fold_of"].keys()), "fold": list(spec["fold_of"].values())}).with_columns(
        pl.col("Cell").cast(pl.Int16), pl.col("fold").cast(pl.Int8))
    n_tot = 0
    for y in years:
        fo = os.path.join(od, f"y{y}.parquet")
        if os.path.exists(fo):
            n_tot += pl.scan_parquet(fo).select(pl.len()).collect().item()
            continue
        lf = raw_training_frame(member, y, cells)
        if mode == "train":
            spec1 = ((pl.col("c_y") >= 1) | (pl.col("c_y1").fill_null(0) >= 1) | (pl.col("G_y") < 0)
                     | (pl.col("G_y1").fill_null(1.0) < 0) | (pl.col("fate_y1") >= 1))
            lf = lf.with_columns(stratum=spec1.cast(pl.Int8)).filter(
                (pl.col("stratum") == 1) | (pl.col("u_hash") < frac)).with_columns(
                w_ip=pl.when(pl.col("stratum") == 1).then(1.0).otherwise(1.0 / frac).cast(pl.Float32))
        else:
            lf = lf.filter(pl.col("u_hash") < frac).with_columns(stratum=pl.lit(-1, pl.Int8),
                                                                w_ip=pl.lit(1.0, pl.Float32))
        keep = list(dict.fromkeys(IDS + RAW_TREE + RAW_PATCH + RAW_LOSS + ["hist_years"] + RAW_CLIM + TARGETS
                                  + ["soil_code"] + [f"c85_{f}" for f in C85_F] + ["stratum", "w_ip", "W_y"]))
        df = lf.select(keep).collect().join(fold, on="Cell", how="left")
        df.write_parquet(fo + ".tmp", compression="zstd")
        os.replace(fo + ".tmp", fo)
        n_tot += df.height
        print(f"  {member} y{y}: {df.height} rows", flush=True)
    return n_tot


def stage_samples(a):
    spec = split_spec(a.split)
    base = os.path.join(SAMPLES, a.split)
    json.dump({k: v for k, v in spec.items() if k != "fold_of"}, open(os.path.join(_mk(base), "split.json"), "w"),
              indent=1)
    jobs = []
    for m in spec["train"]:
        jobs.append(("train", m, os.path.join(base, "train"), "train", REST_FRAC, spec["cells_train"]))
    for s, ms in spec["heldout"].items():
        cells = spec["cells_f5"] if s == "F5" else spec["cells_dev"]
        for m in ms:
            jobs.append((s, m, os.path.join(base, "eval", s), "eval", EVAL_FRAC, cells))
    if a.member:
        jobs = [j for j in jobs if j[1] in a.member and (not a.set or j[0] in a.set)]
    if a.set:
        jobs = [j for j in jobs if j[0] in a.set]
    for s, m, od, mode, frac, cells in jobs:
        t0 = time.time()
        n = sample_member(spec, m, od, mode, frac, cells)
        status(f"A1 samples {a.split} {s} {m}: {n} rows ({time.time() - t0:.0f} s)")


def _mk(d):
    os.makedirs(d, exist_ok=True)
    return d


# ------------------------------------------------------------------------------------------------ recruit samples
def patch_type_comp(member: str, year: int, cells: list[int], types: list[int]) -> tuple[pl.DataFrame, pl.DataFrame]:
    """Per (Cell, Patch) and per Cell at y: living printed stem counts and agb by tree Type (from SH3 rows)."""
    files = [f for f in trans_files(member) if f.endswith(f"y{year}.parquet")]
    t = pl.scan_parquet(files[0]).filter(pl.col("Cell").is_in(cells)).select(
        "Cell", "Patch", "Type", pl.col("agb").cast(pl.Float64)).collect()
    return comp_from_trees(t, types)


def comp_from_trees(t: pl.DataFrame, types: list[int]) -> tuple[pl.DataFrame, pl.DataFrame]:
    """Shared by training and rollout: per-patch and per-cell composition by Type from (Cell, Patch, Type, agb)."""
    pt = t.group_by("Cell", "Patch", "Type").agg(n=pl.len(), a=pl.col("agb").cast(pl.Float64).sum())
    ce = t.group_by("Cell", "Type").agg(n=pl.len(), a=pl.col("agb").cast(pl.Float64).sum())
    P = t.select("Cell", "Patch").unique()
    C = t.select("Cell").unique()
    for k in types:
        P = P.join(pt.filter(pl.col("Type") == k).select("Cell", "Patch", pl.col("n").alias(f"pt_n_t{k}"),
                                                          pl.col("a").alias(f"pt_agb_t{k}")),
                   on=["Cell", "Patch"], how="left")
        C = C.join(ce.filter(pl.col("Type") == k).select("Cell", pl.col("n").alias(f"ce_n_t{k}"),
                                                          pl.col("a").alias(f"ce_agb_t{k}")), on="Cell", how="left")
    P = P.fill_null(0)
    C = C.fill_null(0)
    nt = sum(pl.col(f"ce_n_t{k}") for k in types)
    at = sum(pl.col(f"ce_agb_t{k}") for k in types)
    C = C.with_columns(*[(pl.col(f"ce_n_t{k}") / nt).cast(pl.Float32).alias(f"ce_share_t{k}") for k in types],
                       *[(pl.col(f"ce_agb_t{k}") / at).cast(pl.Float32).alias(f"ce_agbshare_t{k}") for k in types])
    return P, C


RECR_TYPES = [1, 2, 3, 4, 5]  # tree PFTs with Germany recruits (checked in `recruits`)
# global venue: all seven tree PFTs recruit (XDE_RECR_TYPES="0,1,2,3,4,5,6"); default = Germany, unchanged
RECR_TYPES = [int(t) for t in os.environ.get("XDE_RECR_TYPES", ",".join(map(str, RECR_TYPES))).split(",")]
RECR_CLIM = [f"anom_{f}" for f in CLIM_F] + [f"anom_{f}" for f in TR20] + sorted(set(ABS_Y1 + ELIG_ABS))


def recruit_features(df, P=None):
    """Recruit-head features (cell / patch level). Same function for training and rollout."""
    P = rl.load_params() if P is None else P
    f32 = pl.Float32
    ex = [pl.col(f"pt_n_t{k}").cast(f32) for k in RECR_TYPES] + [pl.col(f"pt_agb_t{k}").cast(f32)
                                                                   for k in RECR_TYPES]
    ex += [pl.col(f"ce_share_t{k}") for k in RECR_TYPES] + [pl.col(f"ce_agbshare_t{k}") for k in RECR_TYPES]
    ex += [pl.col(c).cast(f32) for c in ["n_live_y", "sum_fpc_y", "sum_agb_y", "frac_loss_lag0"]]
    return df.with_columns(ex)


def recruit_cols():
    c = ([f"pt_n_t{k}" for k in RECR_TYPES] + [f"pt_agb_t{k}" for k in RECR_TYPES]
         + [f"ce_share_t{k}" for k in RECR_TYPES] + [f"ce_agbshare_t{k}" for k in RECR_TYPES]
         + ["n_live_y", "sum_fpc_y", "sum_agb_y", "frac_loss_lag0"] + [f"grass{t}_fpc_y" for t in GRASS_TYPES]
         + [f"elig_t{k}_y1" for k in RECR_TYPES] + ["n_elig_y1"]
         + [f"{c}_y1" for c in RECR_CLIM] + ["soil_code"] + [f"c85_{f}" for f in C85_F])
    return c


def add_eligibility(df: pl.DataFrame, P=None) -> pl.DataFrame:
    """rl.eligible on the y+1 climate (20-yr tcold/twarm, current gdd5, prec_ann) — the C-faithful basis."""
    P = rl.load_params() if P is None else P
    E = rl.eligible(df["tcold_month_tr20_y1"].to_numpy(), df["twarm_month_tr20_y1"].to_numpy(),
                    df["gdd5_y1"].to_numpy(), df["prec_ann_y1"].to_numpy(), P)
    return df.with_columns(*[pl.Series(f"elig_t{k}_y1", E[:, k].astype(np.float32)) for k in RECR_TYPES],
                           pl.Series("n_elig_y1", E[:, :MAX_TREE_TYPE + 1].sum(axis=1).astype(np.float32)))


def stage_recruits(a):
    spec = split_spec(a.split)
    base = _mk(os.path.join(SAMPLES, a.split, "recruits"))
    jobs = [("train", m, spec["cells_train"]) for m in spec["train"]]
    jobs += [("F5", m, spec["cells_f5"]) for m in spec["train"]]
    for s in ("GCM", "SCEN", "SEED2"):
        jobs += [(s, m, spec["cells_dev"]) for m in spec["heldout"][s]]
    P = rl.load_params()
    fold = pl.DataFrame({"Cell": list(spec["fold_of"].keys()), "fold": list(spec["fold_of"].values())}).with_columns(
        pl.col("Cell").cast(pl.Int16), pl.col("fold").cast(pl.Int8))
    for s, m, cells in jobs:
        fo = os.path.join(_mk(os.path.join(base, s)), f"{m}.parquet")
        if os.path.exists(fo):
            continue
        t0 = time.time()
        gcm = spec["rows"][m]["gcm"]
        parts = []
        for f in sorted(glob.glob(os.path.join(RECRT, CELLSET, m, "cb=*", "y*.parquet"))):
            y = int(os.path.basename(f)[1:5])
            R = pl.read_parquet(f).filter(pl.col("Cell").is_in(cells) & (pl.col("Type") <= MAX_TREE_TYPE))
            if R.height == 0:
                continue
            Pc, Cc = patch_type_comp(m, y, cells, RECR_TYPES)
            ph = pl.read_parquet(patch_file(m, y)).select("Cell", "Patch", "Year", "frac_loss_lag0")
            R = (R.drop("frac_loss_lag0").join(Pc, on=["Cell", "Patch"], how="left")
                 .join(Cc, on="Cell", how="left").join(ph, on=["Cell", "Patch", "Year"], how="left"))
            for k in RECR_TYPES:
                R = R.with_columns(pl.col(f"pt_n_t{k}").fill_null(0), pl.col(f"pt_agb_t{k}").fill_null(0.0))
            R = tr.join_climate(R, cols=RECR_CLIM, years=("y1",), ext=True)
            R = add_eligibility(R, P).join(statics(gcm), on="Cell", how="left")
            parts.append(R)
        D = pl.concat(parts, how="diagonal_relaxed").join(fold, on="Cell", how="left")
        D = D.with_columns(member=pl.lit(m), u_rec=pl.Series(tr.u_hash(D, m)))
        D.write_parquet(fo, compression="zstd")
        status(f"A1 recruits {s} {m}: {D.height} rows ({time.time() - t0:.0f} s)")


# ------------------------------------------------------------------------------------------------ rollout frame
def roster_raw(state, clim_y: pl.DataFrame, clim_y1: pl.DataFrame, gcm: str) -> pl.DataFrame:
    """The raw-column frame of the ROLLOUT, built only from the engine's RosterState and the climate provider's
    frames of y and y+1 (cell order = state.cell['cells']). Rows = every tree of the state (hidden ones included,
    so the output aligns with state.tree); patch/cell context counts PRINTED living trees only, like the table."""
    t = state.tree
    n = state.n
    vis = ~np.asarray(t["hidden"], bool) & ~np.asarray(t["isdead"], bool)
    pidx = state.patch_index()
    npt = len(state.cell["cells"]) * state.npatch
    fpc = np.where(vis, t["fpc_ind"].astype(np.float64), 0.0)
    agb = np.where(vis, t["agb"].astype(np.float64), 0.0)
    n_live = np.bincount(pidx, weights=vis.astype(np.float64), minlength=npt)
    s_fpc = np.bincount(pidx, weights=fpc, minlength=npt)
    s_agb = np.bincount(pidx, weights=agb, minlength=npt)
    H = t["Height"].astype(np.float64)
    # height rank ('min' method, descending) and fpc of strictly taller printed stems, within the patch
    order = np.lexsort((-H, pidx))
    ps, hs, fs, vs = pidx[order], H[order], fpc[order], vis[order]
    rank = np.zeros(n, np.int64)
    above = np.zeros(n, np.float64)
    if n:
        newp = np.r_[True, ps[1:] != ps[:-1]]
        newh = newp | np.r_[True, hs[1:] != hs[:-1]]
        cvis = np.cumsum(vs)
        cfpc = np.cumsum(fs)
        pstart = np.maximum.accumulate(np.where(newp, np.arange(n), 0))
        hstart = np.maximum.accumulate(np.where(newh, np.arange(n), 0))
        base_v = np.where(pstart > 0, cvis[pstart - 1], 0)
        base_f = np.where(pstart > 0, cfpc[pstart - 1], 0.0)
        before_v = np.where(hstart > 0, cvis[hstart - 1], 0) - base_v
        before_f = np.where(hstart > 0, cfpc[hstart - 1], 0.0) - base_f
        rank[order] = before_v + 1
        above[order] = before_f
    ci = state.cell_index(t["Cell"])
    ncell = len(state.cell["cells"])
    cell_n = np.bincount(ci, weights=vis.astype(np.float64), minlength=ncell)
    ring = state.patch["loss_ring"]
    raw = {k: t[k] for k in ["Type"] + TRAITS + ["Height", "agb", "vegc", "LAI", "fpc_ind", "D95", "Age"]}
    raw.update({"Cell": t["Cell"], "Patch": t["Patch"], "c_y": t["c"], "G_y": t["G"],
                "d_agb_prev": t["d_agb_prev"], "is_new_y": np.asarray(state.aux_tree.get(
                    "is_new", np.zeros(n, bool)), bool),
                "n_live": n_live[pidx].astype(np.int16), "sum_fpc": s_fpc[pidx].astype(np.float32),
                "sum_agb": s_agb[pidx].astype(np.float32), "height_rank": rank.astype(np.int16),
                "fpc_above": above.astype(np.float32),
                "cell_stems_per_patch": (cell_n[ci] / state.npatch).astype(np.float32)})
    for g in grass_cols():
        raw[g] = state.patch[g][pidx] if g in state.patch else np.full(n, np.nan, np.float32)
    for k in range(NLAG):
        raw[f"frac_loss_lag{k}"] = ring[pidx, k]
    df = pl.DataFrame(raw)
    for suf, cf in (("y", clim_y), ("y1", clim_y1)):
        c = cf.select(pl.col("Cell").cast(pl.Int16), *[pl.col(x).alias(f"{x}_{suf}") for x in CLIM_COLS])
        df = df.join(c, on="Cell", how="left", maintain_order="left")
    df = df.join(statics(gcm), on="Cell", how="left", maintain_order="left")
    assert df.height == n
    return df


def init_conventions(state, spinin: np.ndarray, start_year: int, chain_first_year: int = 1985):
    """Rollout convention for an SH5 start roster, matching the training table: a tree not printed in the year
    before the start (SH5 `spinin`) has an unknown last-year change (d_agb_prev = NaN, as the table's null) and is
    'new' (is_new_y = True) — except at the chain's first year, where the table has no previous year at all and
    carries is_new_y = null (-> False) for every tree."""
    spinin = np.asarray(spinin, bool)
    state.tree["d_agb_prev"] = np.where(spinin, np.nan, state.tree["d_agb_prev"]).astype(np.float32)
    state.aux_tree["is_new"] = spinin & (start_year > chain_first_year)


# ------------------------------------------------------------------------------------------------ audit
def stage_audit(a):
    """Rebuild the rollout frame from an SH5 initial state (MPI Historical s1 2014 by default) and the engine's
    climate provider, and compare every B0/B1/derived feature with the training frame (SH3 + join_climate) of the
    same trees and year (the ssp member's y = 2014 rows). Hidden state that the init fills differently (spin-in
    d_agb_prev) is reported, not hidden."""
    import explore_de_engine as en
    spec = split_spec(a.split)
    m = a.audit_member or [x for x in spec["train"] if "ssp" in x][0]
    row = spec["rows"][m]
    gcm, seed, scen = row["gcm"], int(row["seed"]), row["scen"]
    Y = 2014
    cells = np.array(spec["cells_dev"][:: max(1, a.audit_stride)], dtype=np.int32)
    state = en.load_init(f"{gcm}_Historical_s{seed}_{Y}", CELLSET, cells)
    init_trees = pl.read_parquet(glob.glob(os.path.join(XDE, "shared", "init", CELLSET,
                                                        f"{gcm}_Historical_s{seed}_{Y}", "cb=*", "trees.parquet"))[0])
    spin = init_trees.filter(pl.col("Cell").is_in(cells.tolist())).sort(["Cell", "Patch", "Type", "ID"])["spinin"]
    # the rollout convention for spin-in trees: unknown last-year change = NaN (as in the chain's first table year)
    init_conventions(state, spin.to_numpy(), Y)
    ch = en.Climate(gcm, "Historical", seed, state.cell["cells"], "actual")
    c1 = en.Climate(gcm, scen, seed, state.cell["cells"], "actual")
    R = roster_raw(state, ch.year(Y), c1.year(Y + 1), gcm)
    R = tr.with_key(R.with_columns(ID=pl.Series(state.tree["ID"])))
    Tt = raw_training_frame(m, Y, cells.tolist()).collect()
    FR = assemble(R)
    FT = assemble(Tt)
    J = FT.join(FR, on=tr.KEY, how="full", suffix="_r", coalesce=True)
    out = {"member": m, "year": Y, "cells": int(len(cells)), "rows_train": FT.height, "rows_roll": FR.height,
           "rows_joined": J.height, "unmatched_train": int(J["log_agb_r"].is_null().sum()),
           "unmatched_roll": int(J["log_agb"].is_null().sum()), "spinin_rows": int(spin.sum()), "features": {}}
    feats = [f for f in dict.fromkeys(B0 + B1 + ["resist"]) if f not in tr.KEY]
    for f in feats:
        x = J[f].cast(pl.Float64).to_numpy()
        y = J[f + "_r"].cast(pl.Float64).to_numpy()
        both_nan = np.isnan(x) & np.isnan(y)
        eq = both_nan | (np.abs(x - y) <= 1e-5 * np.maximum(1.0, np.abs(x)))
        out["features"][f] = {"n": int(len(x)), "mismatch": int((~eq).sum()),
                              "max_abs_diff": float(np.nanmax(np.abs(x - y))) if (~both_nan).any() else 0.0}
    bad = {f: v for f, v in out["features"].items() if v["mismatch"]}
    out["features_with_mismatch"] = bad
    out["pass"] = (not bad or set(bad) <= {"d_agb_prev", "rel_dagb_prev"}) and out["unmatched_train"] == 0 \
        and out["unmatched_roll"] == 0
    if bad.get("d_agb_prev"):
        out["note_d_agb_prev"] = ("mismatch rows must equal the spin-in rows whose training value is known: the "
                                  "init fills them with a per-Type median; the rollout convention sets NaN")
        dm = J.filter(pl.col("d_agb_prev").is_not_null() & pl.col("d_agb_prev_r").is_null()).height
        out["d_agb_prev_mismatch_explained_by_spinin"] = int(dm)
    json.dump(out, open(os.path.join(_mk(os.path.join(SAMPLES, a.split)), "audit.json"), "w"), indent=1)
    status(f"A1 audit {m} {Y}: pass={out['pass']}, mismatching features {sorted(bad)}")
    print(json.dumps({k: v for k, v in out.items() if k != "features"}, indent=1), flush=True)


# ------------------------------------------------------------------------------------------------ report
def stage_report(a):
    spec = split_spec(a.split)
    base = os.path.join(SAMPLES, a.split)
    rep = {"item": "A1", "split": a.split, "val_fold": spec["val_fold"], "train_members": spec["train"],
           "heldout": spec["heldout"], "n_cells": {"train": len(spec["cells_train"]), "f5": len(spec["cells_f5"])},
           "feature_sets": {"B0": B0, "B1": B1, "B1_model_inputs": B1_IN, "next_state": NEXT},
           "rest_frac": REST_FRAC, "eval_frac": EVAL_FRAC, "samples": {}}
    tr_files = glob.glob(os.path.join(base, "train", "*", "*.parquet"))
    if tr_files:
        s = pl.scan_parquet(tr_files).group_by("stratum", "fold").agg(n=pl.len(), w=pl.col("w_ip").sum()).collect()
        rep["samples"]["train"] = s.sort("stratum", "fold").to_dicts()
        rep["samples"]["train_rows"] = int(s["n"].sum())
        rep["samples"]["train_weighted_rows"] = float(s["w"].sum())
    for st in ("F5", "GCM", "SCEN", "SEED2"):
        f = glob.glob(os.path.join(base, "eval", st, "*", "*.parquet"))
        if f:
            rep["samples"][st] = int(pl.scan_parquet(f).select(pl.len()).collect().item())
    for st in ("train", "F5", "GCM", "SCEN", "SEED2"):
        f = glob.glob(os.path.join(base, "recruits", st, "*.parquet"))
        if f:
            rep["samples"][f"recruits_{st}"] = int(pl.scan_parquet(f).select(pl.len()).collect().item())
    au = os.path.join(base, "audit.json")
    if os.path.exists(au):
        A = json.load(open(au))
        rep["audit"] = {k: v for k, v in A.items() if k != "features"}
    rep["feature_sources"] = feature_sources()
    json.dump(rep, open(REPORT, "w"), indent=1)
    print(json.dumps({k: v for k, v in rep.items() if k not in ("feature_sources",)}, indent=1)[:4000])


def feature_sources() -> dict:
    """Where each feature comes from in training vs in the rollout (the feature audit's map)."""
    src = {}
    for f in B0:
        if f in TRAITS or f == "Type":
            src[f] = ("SH3 row", "state.tree (immutable)")
        elif f in ("Height", "LAI", "fpc_ind", "D95", "Age", "log_agb", "log_vegc"):
            src[f] = ("SH3 row", "state.tree (updated by the growth/closure heads + allometry; Age += 1)")
        elif f in ("c_y", "G_y"):
            src[f] = ("SH3 recovered hidden state", "state.tree c, G (G sampled by the growth-efficiency head, c by "
                      "the counter rule)")
        elif f in ("d_agb_prev", "rel_dagb_prev", "is_new"):
            src[f] = ("SH3 history columns", "stepper: d_agb_prev = agb_y1 - agb_y; NaN + aux_tree is_new for "
                      "recruits and spin-in trees")
        elif f.startswith("flo"):
            src[f] = ("SH4 frac_loss_lag*", "state.patch loss_ring (engine-owned)")
        elif f.startswith("grass"):
            src[f] = ("SH3 grass columns", "state.patch grass* (grass head or persistence)")
        elif f.startswith("c85_") or f == "soil_code":
            src[f] = ("SH1 clim8514 / cell_static", "same tables (static per cell)")
        else:
            src[f] = ("SH3 patch/cell context", "recomputed from printed living trees of the state (roster_raw)")
    for f in B1:
        src[f] = ("tr.join_climate (y, y+1)", "Climate provider frames: y+1 = step()'s clim_y1, y = the previous "
                  "step's clim_y1 cached by the stepper (first step: provider read in init)")
    return src


# ------------------------------------------------------------------------------------------------ submit
def stage_submit(a):
    logs = os.path.join(REPO, "logs")
    os.makedirs(logs, exist_ok=True)
    jobs = os.path.join(_mk(os.path.join(TAB, "_jobs")), f"A1_{a.what}.sh")
    me = os.path.abspath(__file__)
    if a.what == "samples":
        spec = split_spec(a.split)
        mems = list(dict.fromkeys(spec["train"] + sum(spec["heldout"].values(), [])))
        lines = [f"{PY} {me} samples --split {a.split} --member {m}" for m in mems]
        with open(jobs + ".tasks", "w") as fh:
            fh.write("\n".join(lines) + "\n")
        body = (f"#!/bin/bash\n#SBATCH --account=waldspektrum --partition=priority --qos=priority\n"
                f"#SBATCH --cpus-per-task=4 --time=02:00:00 --array=1-{len(lines)}%6\n"
                f"#SBATCH --job-name=X-de-A1-samples --output={logs}/X-de-A1-samples.%A_%a.out\n"
                f"export POLARS_MAX_THREADS=4\n"
                f"eval \"$(sed -n ${{SLURM_ARRAY_TASK_ID}}p {jobs}.tasks)\"\n")
    else:
        body = (f"#!/bin/bash\n#SBATCH --account=waldspektrum --partition=priority --qos=priority\n"
                f"#SBATCH --cpus-per-task=8 --time=02:00:00\n"
                f"#SBATCH --job-name=X-de-A1-{a.what} --output={logs}/X-de-A1-{a.what}.%j.out\n"
                f"export POLARS_MAX_THREADS=8\n{PY} {me} {a.what} --split {a.split}\n")
    with open(jobs, "w") as fh:
        fh.write(body)
    out = os.popen(f"sbatch {jobs}").read().strip()
    status(f"A1 submit {a.what}: {out} ({jobs})")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("stage", choices=["samples", "recruits", "audit", "report", "submit"])
    ap.add_argument("--split", default="DEV-A")
    ap.add_argument("--member", nargs="*")
    ap.add_argument("--set", nargs="*")
    ap.add_argument("--what", default="samples")
    ap.add_argument("--audit-member", default=None)
    ap.add_argument("--audit-stride", type=int, default=1)
    a = ap.parse_args()
    {"samples": stage_samples, "recruits": stage_recruits, "audit": stage_audit, "report": stage_report,
     "submit": stage_submit}[a.stage](a)


if __name__ == "__main__":
    main()
