#!/usr/bin/env julia
# ─────────────────────────────────────────────────────────────────────────────
# gen_diagrams.jl — code-DERIVED Mermaid diagrams (ENGINEERING_STANDARDS §5(ii)).
#
# Reads the model's OWN component/flux registry (`src/registry.jl`: `COMPONENTS`,
# `FLUXES` — the SOURCE OF TRUTH) and emits Mermaid text to `docs/src/generated/`:
#
#   • dataflow.mmd    `flowchart LR` — ATM/S/F/E nodes, edges labelled by
#                     payload + timescale (thick `==>` = conserved handoff),
#                     ML/physics/hybrid/external nodes styled distinctly.
#   • components.mmd  component overview — one node per component with kind + timescale.
#
# These are ALWAYS TRUE (regenerated from the registry) and act as a DIFF ALARM:
# if the registry changes, these files change, and CI (`--check`) fails until the
# committed diagrams — and the hand-authored curated ones in
# `docs/src/assets/diagrams/` — are brought back in sync.
#
# Base-only (no external packages): runnable in the Phase-0 dependency-free package.
#
# Usage:
#   julia --project=. scripts/gen_diagrams.jl            # (re)write the .mmd files
#   julia --project=. scripts/gen_diagrams.jl --check    # CI: exit 1 if stale
#
# `--check` is the `git diff --exit-code -- docs/src/generated` equivalent.
# ─────────────────────────────────────────────────────────────────────────────

using LPJmLFITEmulator   # brings COMPONENTS, FLUXES, Component, Flux into scope

# ── Paths (relative to this script, so it is CWD-independent) ────────────────
const REPO_ROOT       = dirname(@__DIR__)
const OUT_DIR         = joinpath(REPO_ROOT, "docs", "src", "generated")
const DATAFLOW_PATH   = joinpath(OUT_DIR, "dataflow.mmd")
const COMPONENTS_PATH = joinpath(OUT_DIR, "components.mmd")

# ── Header stamped into every generated file ─────────────────────────────────
const HEADER = join(
    (
        "%% AUTO-GENERATED by scripts/gen_diagrams.jl — DO NOT EDIT",
        "%% Source of truth: src/registry.jl (COMPONENTS, FLUXES).",
        "%% Regenerate: julia --project=. scripts/gen_diagrams.jl",
    ),
    "\n",
)

# Make free text safe for Mermaid: `\"` closes a quoted label, `|` delimits edge
# labels. Everything else (commas, parens, =, ·, ₂, →) is fine as literal text.
sanitize(s) = replace(String(s), '"' => '\'', '|' => '/')

# Distinct visual styling per component `kind` — the ML node(s) stand out (§5(i)).
const KIND_CLASSDEF = Dict(
    :ml       => "classDef ml fill:#fde68a,stroke:#b45309,stroke-width:3px,color:#111827;",
    :physics  => "classDef physics fill:#bfdbfe,stroke:#1e40af,stroke-width:2px,color:#111827;",
    :hybrid   => "classDef hybrid fill:#bbf7d0,stroke:#15803d,stroke-width:2px,color:#111827;",
    :external => "classDef external fill:#e5e7eb,stroke:#374151,stroke-width:1px,color:#111827,stroke-dasharray:5 4;",
)

"Emit `classDef` lines (only for kinds present) + one `class <id> <kind>` per node."
function emit_styles(io, components)
    kinds = unique(c.kind for c in components)
    for k in kinds
        haskey(KIND_CLASSDEF, k) && println(io, "    ", KIND_CLASSDEF[k])
    end
    for c in components
        haskey(KIND_CLASSDEF, c.kind) && println(io, "    class $(c.id) $(c.kind);")
    end
    return io
end

"`flowchart LR` of the four subsystems; edges carry payload + timescale."
function render_dataflow(components, fluxes)
    io = IOBuffer()
    println(io, HEADER)
    println(io, "flowchart LR")
    println(io, "    %% Nodes = subsystems (kept subsystem-level per the Mermaid caveats, §5).")
    for c in components
        label = "$(c.id) — $(sanitize(c.name))<br/>[$(c.kind) · $(c.timescale)]"
        println(io, "    $(c.id)[\"$(label)\"]")
    end
    println(io, "    %% Edges = fluxes/handoffs; thick ==> marks a CONSERVED handoff.")
    for f in fluxes
        arrow = f.conserved ? "==>" : "-->"
        tag   = f.conserved ? "$(f.timescale) · conserved" : String(f.timescale)
        label = "$(sanitize(f.payload))<br/>[$(tag)]"
        println(io, "    $(f.from) $(arrow)|\"$(label)\"| $(f.to)")
    end
    emit_styles(io, components)
    return String(take!(io))
end

"`flowchart TB` component overview: one node per component with kind + timescale + description."
function render_components(components)
    io = IOBuffer()
    println(io, HEADER)
    println(io, "flowchart TB")
    println(io, "    %% Component overview (kind / timescale) — derived from COMPONENTS.")
    for c in components
        label = "<b>$(c.id)</b> — $(sanitize(c.name))<br/>kind: $(c.kind) · timescale: $(c.timescale)<br/>$(sanitize(c.description))"
        println(io, "    $(c.id)[\"$(label)\"]")
    end
    emit_styles(io, components)
    return String(take!(io))
end

# ── Targets: (path, generated-content) pairs ─────────────────────────────────
targets() = (
    (DATAFLOW_PATH,   render_dataflow(COMPONENTS, FLUXES)),
    (COMPONENTS_PATH, render_components(COMPONENTS)),
)

"Write the generated diagrams to `docs/src/generated/`."
function generate()
    mkpath(OUT_DIR)
    for (path, content) in targets()
        write(path, content)
        println("wrote $(relpath(path, REPO_ROOT))")
    end
    return nothing
end

"""
Regenerate to a temp dir and compare against the committed files.
Exit 1 if any differ (CI staleness gate; `git diff --exit-code` equivalent).
"""
function check()
    tmp = mktempdir()
    stale = String[]
    for (path, content) in targets()
        tmpf = joinpath(tmp, basename(path))
        write(tmpf, content)
        committed = isfile(path) ? read(path, String) : ""
        if read(tmpf, String) != committed
            push!(stale, relpath(path, REPO_ROOT))
        end
    end
    if isempty(stale)
        println("--check OK: committed diagrams match the registry.")
        return 0
    else
        println(stderr, "--check FAILED: these derived diagrams are STALE (rerun scripts/gen_diagrams.jl):")
        for s in stale
            println(stderr, "  • $(s)")
        end
        return 1
    end
end

function main(args)
    if "--check" in args
        exit(check())
    else
        generate()
    end
end

main(ARGS)
